### ISSUE TITLE
Design Contact us page

### ISSUE THREAD

**Issue by PulsaraSandeepa** [PulsaraSandeepa/FoodRecipeApp-flutter#12]

**Comment by PulsaraSandeepa** [comment]
![Screenshot (127)](https://user-images.githubusercontent.com/50085017/107125169-3fed4c80-68ce-11eb-8571-a72004ea779c.png)

- when the button click set to open the phone caller

**Comment by PulsaraSandeepa** [comment]
- @DamithaNeranjan design this page as the about us page.
 - keep the contact us button
 - add the functionality to the button when clicked open the caller to a contact number of us.

**Comment by DamithaNeranjan** [comment]
- @PulsaraSandeepa Can you please mention how the page contents should be arranged. A doodle drawing on the above given screen shot would be preferable.

- Do you need many about us pages to each and every person in the organization or you need only one common about us page?

**Comment by PulsaraSandeepa** [comment]
- this is the contact us page
 - we need only one about us page and it's already done.
 - I will attach a mock UI for the requirement

**Comment by PulsaraSandeepa** [comment]
![Screenshot (128)_LI](https://user-images.githubusercontent.com/50085017/108456755-0554be00-7297-11eb-845b-6fb79e07126e.jpg)

**Comment by DamithaNeranjan** [comment]
![Contact Us Page test](https://user-images.githubusercontent.com/41992701/109609532-7591f800-7b51-11eb-8047-4fa8b18d7866.png)

- @PulsaraSandeepa the social network icons are linked to dummy urls for now. We can change them when we have accounts for them. I have only linked the facebook account for now.
- I'm not sure of the styling I used, please check and mention if any changes to be made.
- I have linked the contact us button to open the dialler when it is clicked with a given phone number. There also I have used a dummy phone number.
