### ISSUE TITLE
Set Recipe page

### ISSUE THREAD

**Issue by PulsaraSandeepa** [PulsaraSandeepa/FoodRecipeApp-flutter#13]

**Comment by PulsaraSandeepa** [comment]
![Screenshot (129)](https://user-images.githubusercontent.com/50085017/107125041-6363c780-68cd-11eb-9615-1334ca8658b3.png)

- recipe page now looks like this
- create the page to display the recipe and image as below 
- free to use your own way of styling

![Screenshot (129)_LI](https://user-images.githubusercontent.com/50085017/107125123-f69cfd00-68cd-11eb-98c5-511f11b530fa.jpg)

**Comment by DamithaNeranjan** [comment]
@PulsaraSandeepa  Check whether the pushed project is up to your expectations.
If any changes or modifications to be done, please mention.
![Recipe view page test](https://user-images.githubusercontent.com/41992701/107737043-82c57f00-6d29-11eb-8201-e0ed0cce66aa.png)

**Comment by PulsaraSandeepa** [comment]
It is awesome😍

**Comment by PulsaraSandeepa** [comment]
Make a pull request from your branch to master
