### ISSUE TITLE
Design About Us page

### ISSUE THREAD

**Issue by PulsaraSandeepa** [PulsaraSandeepa/FoodRecipeApp-flutter#17]

**Comment by PulsaraSandeepa** [comment]
![Screenshot (127)_LI](https://user-images.githubusercontent.com/50085017/107124752-b76dac80-68cb-11eb-91d9-6c60036b1a88.jpg)

 - Change the current widget according to the above format, free to choose your own way to design

**Comment by PulsaraSandeepa** [comment]
![hException](https://user-images.githubusercontent.com/50085017/107962131-a3f9ca00-6fcc-11eb-86a7-d446e66aaa40.png)
here you can download the logo

**Comment by DamithaNeranjan** [comment]
I have redesigned the about us page, check whether it is OK. If any changes to be done, please mention.
![About Us page test](https://user-images.githubusercontent.com/41992701/108218662-e7823e80-715a-11eb-820c-2b2f01e8d157.png)

**Comment by PulsaraSandeepa** [comment]
❤
